- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - { role: devsec.hardening.ssh_hardening, tags: ssh }
    - { role: tailscale,                      tags: tailscale }
