- name: Ensure {{ tailscale_dir }} exists
  become: true
  ansible.builtin.file:
    path: "{{ tailscale_dir }}"
    state: directory
    mode: 700

- name: Copy OAuth secret to authkey file
  become: true
  ansible.builtin.copy:
    src: "files/authkey"
    dest: "{{ tailscale_dir }}/authkey"
    mode: 600
    owner: root
    group: root

- name: Setup tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale.machine
  vars:
    tailscale_authkey: "file:{{ tailscale_dir }}/authkey"
    tailscale_tags: "{{ pavillion_tailscale_tags }}"
    # tailscale_args: "--reset --force-reauth"

- name: Add tailscale0 interface to trusted zone
  become: true
  firewalld:
    zone: trusted
    interface: tailscale0
    permanent: true
    state: enabled
  notify:
    - Restart firewalld
    - Restart tailscaled
